### PR TITLE
clearinv option in smite (FS-161)

### PR DESCRIPTION
**Pull request by Elmon11**
https://forum.totalfreedom.me/d/1142-remove-clearing-inventories-from-smite/4

### CODE REVIEW

**Comment by Wild1145** [comment]
Given the suggestion is yet to be approved much less a Jira ticket raised to do anything about adding it, I'll convert this PR to a draft for now pending the outcome of that ticket.

**Comment by Wild1145** [comment]
You're also getting a build failure. 

`[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  20.966 s

[INFO] Finished at: 2021-03-21T13:03:18Z

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project TotalFreedomMod: Compilation failure: Compilation failure: 

[ERROR] /home/travis/build/AtlasMediaGroup/TotalFreedomMod/src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java:[57,14] cannot find symbol

[ERROR]   symbol:   variable args

[ERROR]   location: class me.totalfreedom.totalfreedommod.command.Command_smite

[ERROR] /home/travis/build/AtlasMediaGroup/TotalFreedomMod/src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java:[57,19] cannot find symbol

[ERROR]   symbol:   variable args

[ERROR]   location: class me.totalfreedom.totalfreedommod.command.Command_smite

[ERROR] -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR] 

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by Elmon11** [comment]
this should work should the suggestion reach a point where we decide to make it so you have to specify clearing inventory

**Review by Paldiu — APPROVED** [review]

**Comment by Focusvity** [comment]
I have raised FS-161 to keep a track of suggestions. Note, this won't be able to be merged until the ticket is out of the backlog.

**Pull request merged**
