### PR TITLE
Bug fixes, improvements, and removals (FS-192)

### PR DESCRIPTION
**Pull request by VideoGameSmash12**
Round 2.

### Bug Fixes
* Fixes /tempban throwing a NullPointerException when trying to get a player who isn't on the server but was in the past (FS-193)
* Fixes /tempban banning players for 24 hours regardless of the duration defined (FS-157)
* Fixes /list -t throwing a NullPointerException when performed from a non-player source (such as Telnet) (FS-195)

### Improvements
* /tempban now kicks players on the same IP address as a banned player (if the banned player is online). (FS-193)
* /tempban now works on both online and offline players. (FS-193)
* Moves globally blocked commands to the `global` subsection of the original `blocked_commands` section. (FS-194)
⚠️ _**WARNING: You *will* need to update your configurations if you have custom blocked command entries.**_ ⚠️
* /wildcard's command blacklist is now configurable under the `wildcard` section in `blocked_commands`. (FS-194)
* The commands muted players can't use are now configurable under the `muted` section in `blocked_commands`. (FS-194)
* The list of words that can't be used in /tag is now configurable under the `forbidden_words` section. (FS-194)

### Removals
* Removes the hubworld entirely (FS-165).
* Removes some commented-out globally blocked command entries. (FS-194)

### CODE REVIEW

**Comment by Wild1145** [comment]
@Focusvity Do you mind raising the tickets appropriate for this PR (As It looks like it'll be a couple) assuming you're happy with everything and update the PR description appropriately?

**Comment by Focusvity** [comment]
I have created tickets for each or a ticket for relating changes.

**Comment by Focusvity** [comment]
While the tickets are made, the changes will not be merged until next month - few tickets that existed were scheduled for next month.

**Review by Focusvity — APPROVED** [review]
Looks good.

**Pull request merged**
