### PR TITLE
block /editsign and aliases in protected worlds

### PR DESCRIPTION
**Pull request by DragonSlayer2189**

### CODE REVIEW

**Review by Paldiu — DISMISSED** [review]

**Review by Wild1145 — CHANGES_REQUESTED** [review]
Does not even compile...

**Comment by DragonSlayer2189** [comment]
I'll take a look and see what went wrong here

**Comment by DragonSlayer2189** [comment]
Holy shit I'm an idiot, I'll fix this when I get home

  [2021-09-19 16:21:56] [autobuild] /home/runner/work/TotalFreedomMod/TotalFreedomMod/src/main/java/me/totalfreedom/totalfreedommod/world/WorldRestrictions.java:[41,126] ';' expected

**Review by Paldiu — DISMISSED** [review]

**Comment by VideoGameSmash12** [comment]
This is a band-aid solution to a problem we can fix in plugins like Itemizer.

**Comment by Focusvity** [comment]
@DragonSlayer2189 Are you going to update the PR?

**Pull request closed without merging**
