### PR TITLE
Hopefully fix my chat colour

### PR DESCRIPTION
**Pull request by Wild1145**
Not sure if this will work but I'm hoping it does.

### CODE REVIEW

**Comment by TFTWPhoenix** [comment]
Saw this open and was curious why maven failed. Apparently where you turned it to red you put `ChatColor.ChatColor.DARK_RED` instead of `ChatColor.DARK_RED`. I'll build this with the changes and see if it works.

**Review by TFTWPhoenix — CHANGES_REQUESTED** [review]
`ChatColor.ChatColor.DARK_RED` to `ChatColor.DARK_RED`.

**Comment by Wild1145** [comment]
image

This appears to work, I tested this out on Freedom-01 when trying to fix another issue so should be good hopefully.

**Review by TFTWPhoenix — APPROVED** [review]
Looks good!

**Comment by smartnt** [comment]
Did this on my side before the PR was even made... now it's on my PR, lol. This can be closed.

**Pull request closed without merging**
