### PR TITLE
Makes spawnmob configurable, increases the default limit to 25 (FS-212)

### PR DESCRIPTION
**Pull request by VideoGameSmash12**
Dead simple.

### CODE REVIEW

**Comment by VideoGameSmash12** [comment]
What the fuck is with Maven these days?

**Comment by Focusvity** [comment]
@VideoGameSmash12 The issue is with BukkitTelnet - might want to check that out.

**Comment by Wild1145** [comment]
Issue has been identified and resolved with Nexus. Checks should now run as expected.

**Review by Focusvity — APPROVED** [review]
LGTM!

**Pull request merged**
