### PR TITLE
Properly fix FS-33

### PR DESCRIPTION
**Pull request by Focusvity**
Had a chat with @abhiram555 about the code and agreed to make a PR to fix players showing up as verified admin.

### CODE REVIEW

**Review by Paldiu — APPROVED** [review]
Imagine adding yourself to dev

**Comment by Paldiu** [comment]
No merging until Ryan approves next merge

**Comment by abhiram555** [comment]
verifiedNoAdmin is a list of people who are admin but do not want admin on that IP. so could you change or to and?

**Comment by Focusvity** [comment]
> verifiedNoAdmin is a list of people who are admin but do not want admin on that IP. so could you change or to and?(|| to &&)

I have changed a few things as double storing verified admins was unneeded.

**Comment by abhiram555** [comment]
hopefully, this wont broke anything lets test it on test server!

**Comment by Focusvity** [comment]
> hopefully, this wont broke anything lets test it on test server!

I already tested it on my test server and it is working as expected.

**Comment by abhiram555** [comment]
Based on your changes. iit will be broken. the #isVerifiedAdmin() need to return true if VerifiedNoAdmin contains there name and VerifiedNoAdminIps doesn't contains there IP. as it supposed to check if they can be admin in that IP if there name contains in VerifiedNoAdmin, so yeah based on your changes that function supposed to be broken.

> > hopefully, this wont broke anything lets test it on test server!
> 
> I already tested it on my test server and it is working as expected.

**Comment by Focusvity** [comment]
> Based on your changes. it will be broken. the #isVerifiedAdmin() need to return true if VerifiedNoAdmin contains there name and VerifiedNoAdminIps doesn't contains there IP. as it supposed to check if they can be admin in that IP if there name contains in VerifiedNoAdmin, so yeah based on your changes that function supposed to be broken.
> 
> > > hopefully, this wont broke anything lets test it on test server!
> > 
> > 
> > I already tested it on my test server and it is working as expected.

I'll explain how verified admin is supposed to work. When you verify an admin impostor (/verifynoadmin), it is supposed to add their name and their IP - See https://github.com/AtlasMediaGroup/TotalFreedomMod/blob/development/src/main/java/me/totalfreedom/totalfreedommod/command/Command_verifynoadmin.java#L35-L57
So when they rejoin, it will remember them on their name and IP instead of manually verifying them every time they rejoin. This won't give them admin permissions but it is useful if they are joining from a place they don't normally join from.

I hope this clears up your confusion on the verified admin feature.

**Comment by abhiram555** [comment]
alright. thanks for the explanation :)

**Comment by Wild1145** [comment]
This is now running on Freedom-01 due to the bug this introduced.

**Comment by Focusvity** [comment]
This resolves FS-144 as well.

**Review by Paldiu — APPROVED** [review]

**Comment by Wild1145** [comment]
The CodeQL Scan can be ignored for this, it was not a changed introduced here and I'll look into it further.

**Pull request merged**
