### PR TITLE
Update all dependencies, confirmed working

### PR DESCRIPTION
**Pull request by Telesphoreo**

### CODE REVIEW

**Review by Taahh — APPROVED** [review]
it good

**Comment by allinkdev** [comment]
:middle_finger:

**Comment by Telesphoreo** [comment]
> Scummy (see #234)

I did it a different way and yours did not work initially because of libsdisguises. Also the checks are broken so I could not have merged yours no matter what because the java 17 build task does not work.

**Comment by allinkdev** [comment]
> > Scummy (see #234)
> 
> I did it a different way and yours did not work initially because of libsdisguises. Also the checks are broken so I could not have merged yours no matter what because the java 17 build task does not work for non members (i think?)

I fixed that in the latest commit. The checks were running when you closed them. And the end result is exactly the same.

**Comment by Taahh** [comment]
duplicate of #234

**Comment by Telesphoreo** [comment]
not a duplicae

**Comment by allinkdev** [comment]
> not a duplicae

(by a few lines)

**Pull request merged**
