### PR TITLE
SQL fix

### PR DESCRIPTION
**Pull request by speedxx**

### CODE REVIEW

**Comment by Wild1145** [comment]
Given the error is that there at 16 values provided with 17 being in the table does this not just remove one of those 16 values? Is it that there are extra columns in the dB table that shouldn't be or that there are entries that should be being passed which are not?

**Comment by speedxx** [comment]
the original error was that players had 15 columns but 16 values were supplied and this was the case because the reddit system got removed, `player.getRedditUsername()` was the 14th value which got removed without a replacement value (my fault)

**Comment by Wild1145** [comment]
@speedxx Will this fix the issue entirely or will we also need to go and make manual changes to the dB table to remove certain columns (I'm guessing so?)

**Comment by speedxx** [comment]
@Wild1145 it should fix the issue entirely

**Review by Paldiu — APPROVED** [review]

**Comment by Wild1145** [comment]
This somehow got bundled into another PR by mistake.

**Pull request merged**
