### PR TITLE
My JIRA tickets fulfilled.

### PR DESCRIPTION
**Pull request by smartnt**

### CODE REVIEW

**Comment by Wild1145** [comment]
Resolves FS-121, FS-40, FS-127. Not sure if it resolves FS-93 though?

**Review by Wild1145 — CHANGES_REQUESTED** [review]
There are two Codacy warnings I'd like to get cleared please, both around un-used imports that were created in this PR. The other warning around the toggleclownfish command can be ignored as that's a bug in itself.

**Comment by Wild1145** [comment]
Happy with the Codacy changes. If a developer can give this a review to make sure they're happy (As I'm certainly not qualified) that'd be appreciated. 

@smartnt if you're able to confirm from my previous comment which issues this specifically resolves as well that would be greatly appreciated!

**Review by Wild1145 — APPROVED** [review]

**Comment by Wild1145** [comment]
Did not mean to approve that how I did, was trying to approve the change I requested, not the entire bloody thing.

**Review by Paldiu — APPROVED** [review]
Looks fine to me

**Comment by smartnt** [comment]
FS-40, FS-121, FS-127

**Pull request merged**
