### PR TITLE
Multiple fixes, one commit

### PR DESCRIPTION
**Pull request by VideoGameSmash12**
Here's a list of things I've fixed/mitigated in this commit:
- Range bans in ban-related commands (FS-209)
- Bug in /tempban where the duration in the broadcast is always wrong
- Over-complicated handling of /tempban durations (instead of trying to process them and silently fail, it'll flat out say that an invalid duration is well, invalid)
- Inconsistent "player not found" messages in banning commands
- (Mitigates) weird issue with case-sensitive usernames in banning commands when the server has restarted since a player last joined
- (Mitigates) banned IPs being inaccurate when a player was banned offline whilst containing multiple IPs in their playerdata
- MovementValidator needing Mojangson at all (related to FS-406)

Here is what I've done in addition:
- Merged /tban and /noob into /tempban, which now bans for 5 minutes by default (FS-205)

### CODE REVIEW

**Comment by Wild1145** [comment]
Not confident enough to review this myself. 

My only thought is I'm not sure if depending on Essentials is ideal, I only skim read but as long as we are trying / gathering data from multiple sources, I'm happy. I just don't want us to be dependent on Essentials for IP / other info if we can help it given we do already store such info.

**Review by Paldiu — APPROVED** [review]
Good to go!

**Comment by VideoGameSmash12** [comment]
why the fuck is it taking 5 billion years to build

**Comment by Wild1145** [comment]
Looks like we've eaten through the bandwidth cap on the free tier for the cache already which isn't ideal. Will be looking at that this week then to get the build working again. Had hoped I would have had more time than I did to sort it!

**Comment by Wild1145** [comment]
Build is now running. @VideoGameSmash12 I've resolved a merge conflict so if you can sanity check it's still as expected that'd be much appreciated!

**Pull request merged**
